// Pigpen logo - two-layer extrusion of the traced artwork layers.
//
// The SVGs this imports are generated; run `make` before opening this in the
// OpenSCAD GUI. The Makefile drives the whole pipeline:
//
//     pigpen_logo.svg -> build/layers/*.png -> build/svg/*.svg -> this file
//
// Sizes here are the defaults. `make` overrides them with -D, so
// `make stl WIDTH_MM=200 DARK_H=4` does what you would expect without editing
// this file.

// Defines ART_W / ART_H / ART_CX / ART_CY: the measured extent of the traced
// artwork, in source pixels. Generated by `make config`. If it is missing,
// OpenSCAD warns that it cannot open the file and the assert below explains
// what to do; the variables are deliberately not given fallbacks here, because
// a stale guess would silently render at the wrong scale.
include <build/config.scad>

/* [Size] */

// Printed width of the artwork, in mm. Height follows from the aspect ratio.
WIDTH_MM = 120;      // [20:1:400]
// Thickness of the dark base layer, in mm.
DARK_H = 1.2;        // [0.2:0.1:20]
// Thickness of the light layer on top, in mm.
LIGHT_H = 1.0;       // [0.2:0.1:20]

// No part of the model may be shorter than this. Opacity and printability are
// satisfied well below 1 mm - the accent is a raised island on a solid base, so
// its width is what makes it fragile, not its height - but a taller accent gives
// a more pronounced relief, reads better at an angle, and leaves room for a full
// stack of top solid layers instead of an almost-all-solid sliver.
MIN_PART_H = 1.0;

/* [Slicing] */

// The layer height you intend to print at. The two colours meet at z = DARK_H,
// and that plane has to land exactly on a layer boundary: if it does not, the
// slicer cannot split the layer and prints the whole of it in one colour, so a
// sliver of the base comes out in the accent filament or the reverse.
LAYER_H = 0.1;       // [0.05:0.05:0.4]
// First layer height, when your profile differs from LAYER_H. Everything above
// the first layer is stacked at LAYER_H, so the first one shifts every boundary.
// 0.2 is what most 0.1 mm profiles use, but not all of them: a profile with a
// 0.15 mm first layer puts DARK_H=1.2 half a layer out, and the assert below
// catches that rather than letting it print wrong.
FIRST_LAYER_H = 0.2; // [0.05:0.05:0.4]

/* [Build] */

// Which solid to emit. Export "dark" and "light" separately for a two-colour
// print; "all" is the combined model.
PART = "all";        // ["all", "dark", "light"]

// How to build the base.
//   silhouette - base is the dark and light layers merged, so the light layer
//                always has something solid underneath it.
//   knockout   - base is the dark layer exactly as drawn.
// With the current artwork these are the same solid: the light details sit
// entirely inside the dark group, so merging adds nothing. They diverge only if
// the artwork changes so that some light detail pokes outside the dark shape,
// which under knockout would leave it floating with nothing supporting it.
BASE_MODE = "silhouette";  // ["silhouette", "knockout"]

// Centre the model on the origin. Off puts the artwork's lower-left at (0,0).
CENTER = true;

/* [Files] */

// Named for the groups they were rendered from in pigpen_logo.svg. `make`
// overrides these with -D; they are the defaults so the file still opens
// standalone in the GUI after a build.
DARK_SVG = "build/svg/base.svg";
LIGHT_SVG = "build/svg/details.svg";
// The two layers merged as masks and traced once, rather than unioned here.
// See BASE_MODE above and the note in the Makefile for why.
BASE_SVG = "build/svg/base-silhouette.svg";

/* [Hidden] */

// Sampled from the original artwork.
DARK_COLOR = "#492517";
LIGHT_COLOR = "#a5a5a5";

// The traced SVGs carry the source canvas in their viewBox as plain user units,
// one unit per source pixel. dpi = 25.4 makes import() treat one user unit as
// one millimetre, which turns the scale factor below into a plain ratio and
// keeps both layers on the same frame.
SVG_DPI = 25.4;

assert(!is_undef(ART_W),
       "build/config.scad is missing or incomplete - run `make` before rendering.");
assert(ART_W > 0 && ART_H > 0, "measured artwork has no extent - re-run `make trace`.");

// Layer counts for the two colours. The base is the first layer plus whole
// layers on top of it; the accent starts from a boundary, so it is whole layers
// all the way. Both have to come out integral.
function whole(x) = abs(x - round(x)) < 1e-6;
DARK_LAYERS = (DARK_H - FIRST_LAYER_H) / LAYER_H + 1;
LIGHT_LAYERS = LIGHT_H / LAYER_H;

assert(DARK_H >= FIRST_LAYER_H,
       str("DARK_H (", DARK_H, ") is thinner than one first layer (", FIRST_LAYER_H, ")."));
assert(whole(DARK_LAYERS),
       str("DARK_H (", DARK_H, ") is not a whole number of layers: it is ",
           DARK_LAYERS, " layers at FIRST_LAYER_H=", FIRST_LAYER_H, " + LAYER_H=",
           LAYER_H, ". The colour boundary would land mid-layer and the slicer ",
           "would print that layer entirely in one filament. Pick DARK_H = ",
           FIRST_LAYER_H, " + n * ", LAYER_H, "."));
assert(whole(LIGHT_LAYERS),
       str("LIGHT_H (", LIGHT_H, ") is not a whole number of layers: it is ",
           LIGHT_LAYERS, " layers at LAYER_H=", LAYER_H,
           ". The top of the accent would land mid-layer."));
assert(LIGHT_LAYERS >= 1,
       "LIGHT_H is thinner than one layer - the accent would not be printed at all.");
assert(DARK_H >= MIN_PART_H,
       str("DARK_H (", DARK_H, ") is below MIN_PART_H (", MIN_PART_H, ")."));
assert(LIGHT_H >= MIN_PART_H,
       str("LIGHT_H (", LIGHT_H, ") is below MIN_PART_H (", MIN_PART_H, ")."));

// Guarded so that a missing config.scad produces the assertion above and
// nothing else; unguarded, OpenSCAD evaluates these first and buries the real
// message under "undefined operation" warnings.
SCALE = is_undef(ART_W) ? 1 : WIDTH_MM / ART_W;
HEIGHT_MM = is_undef(ART_H) ? 0 : ART_H * SCALE;

echo(str("pigpen: ", WIDTH_MM, " x ", HEIGHT_MM, " x ", DARK_H + LIGHT_H,
         " mm  (base=", BASE_MODE, ", part=", PART, ", ",
         round(DARK_LAYERS), "+", round(LIGHT_LAYERS), " layers at ", LAYER_H, "mm)"));

// Pull one traced layer into place: scaled to the requested width and shifted so
// the *combined* artwork, not this layer's own extent, lands on the origin. Both
// layers get the identical transform, which is what keeps them registered.
module placed(file) {
    offset_xy = CENTER ? [-ART_CX, -ART_CY] : [-ART_X0, -ART_Y0];
    scale(SCALE)
        translate(offset_xy)
            import(file, dpi = SVG_DPI, center = false);
}

module base_2d() {
    if (BASE_MODE == "silhouette") {
        // Deliberately a single import, not union(placed(DARK), placed(LIGHT)).
        // Unioning two separately traced outlines that run along a shared edge
        // produces contours touching at single points, and extruding that
        // yields a mesh CGAL will not accept. The merge is done on the masks
        // before tracing instead.
        placed(BASE_SVG);
    } else if (BASE_MODE == "knockout") {
        placed(DARK_SVG);
    } else {
        assert(false, str("BASE_MODE must be \"silhouette\" or \"knockout\", got \"",
                          BASE_MODE, "\""));
    }
}

module dark_part() {
    color(DARK_COLOR)
        linear_extrude(height = DARK_H)
            base_2d();
}

module light_part() {
    color(LIGHT_COLOR)
        translate([0, 0, DARK_H])
            linear_extrude(height = LIGHT_H)
                placed(LIGHT_SVG);
}

module pigpen() {
    if (PART == "dark") {
        dark_part();
    } else if (PART == "light") {
        light_part();
    } else if (PART == "all") {
        dark_part();
        light_part();
    } else {
        assert(false, str("PART must be \"all\", \"dark\" or \"light\", got \"", PART, "\""));
    }
}

pigpen();
