// Pigpen logo - two-layer extrusion of the traced XCF layers.
//
// The SVGs this imports are generated; run `make` before opening this in the
// OpenSCAD GUI. The Makefile drives the whole pipeline:
//
//     pigpen_logo.xcf -> build/layers/*.png -> build/svg/*.svg -> this file
//
// Sizes here are the defaults. `make` overrides them with -D, so
// `make stl WIDTH_MM=200 DARK_H=4` does what you would expect without editing
// this file.

// Defines ART_W / ART_H / ART_CX / ART_CY: the measured extent of the traced
// artwork, in source pixels. Generated by `make config`. If it is missing,
// OpenSCAD warns that it cannot open the file and the assert below explains
// what to do; the variables are deliberately not given fallbacks here, because
// a stale guess would silently render at the wrong scale.
include <build/config.scad>

/* [Size] */

// Printed width of the artwork, in mm. Height follows from the aspect ratio.
WIDTH_MM = 120;      // [20:1:400]
// Thickness of the dark base layer, in mm.
DARK_H = 3.5;        // [0.2:0.1:20]
// Thickness of the light layer that sits on top of the base, in mm.
LIGHT_H = 3.5;       // [0.2:0.1:20]

/* [Build] */

// Which solid to emit. Export "dark" and "light" separately for a two-colour
// print; "all" is the combined model.
PART = "all";        // ["all", "dark", "light"]

// How to build the base. In the source artwork the light details are knocked
// *out* of the dark layer, so the two are complementary rather than stacked.
//   silhouette - base is dark + light merged, so the light layer always has
//                something solid underneath it. This is the printable choice.
//   knockout   - base is the dark layer exactly as drawn, holes and all. The
//                light layer then floats above those holes with nothing
//                supporting it. Useful for inspecting the artwork, not for
//                printing.
BASE_MODE = "silhouette";  // ["silhouette", "knockout"]

// Centre the model on the origin. Off puts the artwork's lower-left at (0,0).
CENTER = true;

/* [Files] */

DARK_SVG = "build/svg/DarkPart.svg";
LIGHT_SVG = "build/svg/LightPart.svg";
// Dark and light merged as masks and traced once, rather than unioned here.
// See BASE_MODE above and the note in the Makefile for why.
BASE_SVG = "build/svg/base-silhouette.svg";

/* [Hidden] */

// Sampled from the original artwork.
DARK_COLOR = "#492517";
LIGHT_COLOR = "#a5a5a5";

// The traced SVGs carry the source canvas in their viewBox as plain user units,
// one unit per source pixel. dpi = 25.4 makes import() treat one user unit as
// one millimetre, which turns the scale factor below into a plain ratio and
// keeps both layers on the same frame.
SVG_DPI = 25.4;

assert(!is_undef(ART_W),
       "build/config.scad is missing or incomplete - run `make` before rendering.");
assert(ART_W > 0 && ART_H > 0, "measured artwork has no extent - re-run `make trace`.");

// Guarded so that a missing config.scad produces the assertion above and
// nothing else; unguarded, OpenSCAD evaluates these first and buries the real
// message under "undefined operation" warnings.
SCALE = is_undef(ART_W) ? 1 : WIDTH_MM / ART_W;
HEIGHT_MM = is_undef(ART_H) ? 0 : ART_H * SCALE;

echo(str("pigpen: ", WIDTH_MM, " x ", HEIGHT_MM, " x ", DARK_H + LIGHT_H,
         " mm  (base=", BASE_MODE, ", part=", PART, ")"));

// Pull one traced layer into place: scaled to the requested width and shifted so
// the *combined* artwork, not this layer's own extent, lands on the origin. Both
// layers get the identical transform, which is what keeps them registered.
module placed(file) {
    offset_xy = CENTER ? [-ART_CX, -ART_CY] : [-ART_X0, -ART_Y0];
    scale(SCALE)
        translate(offset_xy)
            import(file, dpi = SVG_DPI, center = false);
}

module base_2d() {
    if (BASE_MODE == "silhouette") {
        // Deliberately a single import, not union(placed(DARK), placed(LIGHT)).
        // The two layers were knocked out of each other, so their traced
        // outlines run along the same edge from opposite sides; unioning them
        // here produces contours that touch at single points, and extruding
        // that yields a mesh CGAL will not accept. The merge is done on the
        // masks before tracing instead.
        placed(BASE_SVG);
    } else if (BASE_MODE == "knockout") {
        placed(DARK_SVG);
    } else {
        assert(false, str("BASE_MODE must be \"silhouette\" or \"knockout\", got \"",
                          BASE_MODE, "\""));
    }
}

module dark_part() {
    color(DARK_COLOR)
        linear_extrude(height = DARK_H)
            base_2d();
}

module light_part() {
    color(LIGHT_COLOR)
        translate([0, 0, DARK_H])
            linear_extrude(height = LIGHT_H)
                placed(LIGHT_SVG);
}

module pigpen() {
    if (PART == "dark") {
        dark_part();
    } else if (PART == "light") {
        light_part();
    } else if (PART == "all") {
        dark_part();
        light_part();
    } else {
        assert(false, str("PART must be \"all\", \"dark\" or \"light\", got \"", PART, "\""));
    }
}

pigpen();
